server:
  port: 3000
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  profiles:
    active: test-data,dev
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5431/product
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    #        use_sql_comments: true
    show-sql: false
    open-in-view: false
  config:
    import: ""
  cloud:
    config:
      uri: "http://localhost:8888"
      request-connect-timeout: 2000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

