server:
  port: 3000
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  profiles:
    active: test-data,dev
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5431/product
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      max-lifetime: 900000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
      minimum-idle: 0
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 15
          time_zone: UTC
        order_updates: true
        order_inserts: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
    open-in-view: false
    show-sql: true

  config:
    import: ""
  cloud:
    config:
      uri: "http://localhost:8888"
      request-connect-timeout: 2000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true