apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    apps: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: order-service
  template:
    metadata:
      labels:
        apps: order-service
    spec:
      containers:
        - name: order-service
          image: zena07/order-service
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://ds-postgres:5432/order_service
            - name: SPRING_PROFILE_ACTIVE
              value: dev
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://ds-postgres:5432/order_service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
