apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    apps: order-service
spec:
  type: ClusterIP
  selector:
    apps: order-service
  ports:
    - protocol: TCP
      port: 83
      targetPort: 3002