apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    apps: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: config-service
  template:
    metadata:
      labels:
        apps: config-service
    spec:
      containers:
        - name: config-service
          image: zena07/dn-config
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"