apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    apps: config-service
spec:
  type: ClusterIP
  selector:
    apps: config-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888