server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
#  config:
#    import: "optional:classpath:"
#  cloud:
#    config:
#      uri: "http://localhost:8888"
#      request-connect-timeout: 2000
#      request-read-timeout: 5000
#      retry:
#        max-attempts: 6
#        initial-interval: 1000
#        max-interval: 2000
#        multiplier: 1.1
#      fail-fast: true
  cloud:
    gateway:
      routes:
        - id : product-route
          uri: ${PRODUCT_SERVICE_URL:http://localhost:3000/api/v1}/product
          predicates:
            - Path=/api/v1/product/**
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:3002/api/v1}/order
          predicates:
            - Path=/api/v1/order/**





