server:
  port: 9080
  tomcat:
    connection-timeout: 3s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
spring:
  application:
    name: authServer
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5431/user_management
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      max-lifetime: 900000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
      minimum-idle: 0
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 15
          time_zone: UTC
        order_updates: true
        order_inserts: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
    open-in-view: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: TRACE
