apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    apps: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: edge-service
  template:
    metadata:
      labels:
        apps: edge-service
    spec:
      containers:
        - name: edge-service
          image: zena07/edge-service
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name:  PRODUCT_SERVICE_URL
              value: http://product-service:300
            - name: SPRING_PROFILE_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name:  ORDER_SERVICE_URL
              value: http://order-service:3002

