spring:
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:8888"
      request-connect-timeout: 2000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: true
#    function:
#      definition: dispatchOrder
#    stream:
#      bindings:
#        dispatchOrder-in-0:
#          destination: order-dispatched
#          group: ${spring.application.name}



management:
  endpoints:
    web:
      exposure:
        include: refresh

client:
  product-service-uri: http://localhost:3000/api/v1
