apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    apps: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: product-service
  template:
    metadata:
      labels:
        apps: product-service
    spec:
      containers:
        - name: product-service
          image: zena07/product-service
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://ds-postgres:5432/product
            - name: SPRING_PROFILE_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 9001
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
            - mountPath: /workspace/config
              name: product-config-volume
        volumes:
          - name: product-config-volume
            configMap:
              name: product-config
              items:
                - key: application.yml

