CREATE TABLE authentication_method
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authentication_method VARCHAR(255),
    client_id             INTEGER,
    CONSTRAINT pk_authenticationmethod PRIMARY KEY (id)
);

CREATE TABLE authority
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT pk_authority PRIMARY KEY (id)
);

CREATE TABLE client
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id     VARCHAR(255),
    client_secret VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE client_token_settings
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    access_token_ttl INTEGER,
    type             VARCHAR(255),
    client_id        INTEGER,
    CONSTRAINT pk_clienttokensettings PRIMARY KEY (id)
);

CREATE TABLE grant_type
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grant_type VARCHAR(255),
    client_id  INTEGER,
    CONSTRAINT pk_granttype PRIMARY KEY (id)
);

CREATE TABLE redirect_url
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url       VARCHAR(255),
    client_id INTEGER,
    CONSTRAINT pk_redirecturl PRIMARY KEY (id)
);

CREATE TABLE scope
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scope     VARCHAR(255),
    client_id INTEGER,
    CONSTRAINT pk_scope PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name  VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE authentication_method
    ADD CONSTRAINT FK_AUTHENTICATIONMETHOD_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE authority
    ADD CONSTRAINT FK_AUTHORITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE client_token_settings
    ADD CONSTRAINT FK_CLIENTTOKENSETTINGS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE grant_type
    ADD CONSTRAINT FK_GRANTTYPE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE redirect_url
    ADD CONSTRAINT FK_REDIRECTURL_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE scope
    ADD CONSTRAINT FK_SCOPE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);