spring:
  profiles:
    active: dev
  application:
    name: delivery-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:8888"
      request-connect-timeout: 2000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false
#    function:
#      definition: pack|label
#
management:
  endpoints:
    web:
      exposure:
        include: refresh
