spring:
  profiles:
    active: dev
  application:
    name: delivery-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:8888"
      request-connect-timeout: 2000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false
    #    function:
    #      definition: pack|label
#    stream:
#      bindings:
#        packlabel-in-0:
#          destination: order-accepted
#          content-type: application/json
#        packlabel-out-0:
#          destination: order-dispatched
#          content-type: application/json
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers: localhost:9093


management:
  endpoints:
    web:
      exposure:
        include: refresh
