apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    apps: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: delivery-service
  template:
    metadata:
      labels:
        apps: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: zena07/delivery-service
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 3006
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_PROFILE_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
