apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    apps: delivery-service
spec:
  type: ClusterIP
  selector:
    apps: delivery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006